name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t flask-app .

      - name: Run Flask app in background
        run: |
          docker run -d --name flask-container -p 8080:5000 flask-app

      - name: Run tests
        run: |
          docker run --rm flask-app python tests.py
